name: List Files and Create JSON and Deploy

on:
  push:
    branches: [main]

jobs:
  list-files-and-create-json:
    runs-on: ubuntu-latest

    env:
      VITE_BASEURL: ${{ secrets.VITE_BASEURL }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: List .png files in images folder
        run: |
          find images/ -type f -name "*.png" > images_list.txt

      - name: Create JSON file
        run: |
          jq -Rs 'split("\n") | map(select(length > 0)) | {"images": .}' images_list.txt > images_list.json

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check for changes
        run: |
          git diff --quiet || echo "::set-output name=changes::true"

      - name: Commit JSON file
        if: ${{steps.check_for_changes.outputs.changes == 'true'}}
        run: |
          git add images_list.json
          git commit -m "Add images_list.json"
          git push

      - name: Install dependencies and build
        if: ${{ contains( join(github.event.commits.*.message, ' '), '#build' ) }}
        run: |
          npm ci
          npm run build

      - name: Deploy
        if: ${{ contains( join(github.event.commits.*.message, ' '), '#build' ) }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
